apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sqs-publisher.fullname" . }}-config
data:
  SQS_QUEUE_URL: "{{ .Values.appConfig.sqsQueue }}"
  S3_BUCKET: "{{ .Values.appConfig.s3bucket }}"
  SQS_MSGS_FILE: "{{ .Values.appConfig.sqsMsgsFile }}"
  AWS_REGION: "{{ .Values.appConfig.awsRegion }}"
